name: Deploy Pages

# 触发条件：在 push 到 gh-pages-source 分支后
on:
  push:
    branches:
      - gh-pages-source

# 任务
jobs:
  # https://github.com/JamesIves/github-pages-deploy-action
  build-and-deploy:
    name: Deploy GitHub Pages
    # 服务器环境： Ubuntu（最新版）
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 生成静态文件
      - name: Install and Build Static Files 🔧
        # 获取在Repo设置的Secret（Client ID、Client Secret）
        env: 
          # Vssue Config
          Platform: github
          Owner: yokefellow
          Repo: yokefellow.github.io
          ClientID: ${{ secrets.VSSUE_CLIENT_ID }}
          ClientSecret: ${{ secrets.VSSUE_CLIENT_SECRET }}

          #Sitemap Config
          SitemapHostname: https://yokefellow.github.io
        run: |
          npm install 
          npm run build
      
       # 如果发布到自定义域名
      # - name: Add the domain 
      #   run: |
      #     cd dist 
      #     echo 'blog.yokefellow.com.cn' > CNAME

      # 部署到 GitHub Pages
      - name: Deploy GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: dist
          CLEAN: true

  sync-and-build:
    name: Sync Gitee Pages
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 重新生成静态文件
      - name: Reinstall and Rebuild Static Files 🔧
        # 获取在Repo设置的Secret（Client ID、Client Secret）
        env: 
          # Vssue Config
          Platform: gitee
          Owner: yokefellow
          Repo: yokefellow
          ClientID: ${{ secrets.VSSUE_GITEE_CLIENT_ID }}
          ClientSecret: ${{ secrets.VSSUE_GITEE_CLIENT_SECRET }}
          
          #Sitemap Config
          SitemapHostname: https://yokefellow.gitee.io
        run: |
          npm install 
          npm run build

      # 如果发布到自定义域名
      # - name: Add the domain 
      #   run: |
      #     cd dist 
      #     echo 'blog.yokefellow.com.cn' > CNAME

      # 将静态文件和源码同步到 Gitee Pages
      - name: Sync Gitee Pages 🌀
        uses: yokefellow/gitee-pages-deploy-action@master
        env:
          # 在 Settings -> Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 替换为你的 Gitee Pages 仓库地址
          gitee_repo: "git@gitee.com:yokefellow/yokefellow.git"
          folder: dist
          git_user_email: yuan1241900094@gmail.com
          git_user_name: yokefellow
          # source_github_remote_branch: gh-pages-source
          # source_gitee_remote_branch: gh-pages-source

      # 实现 Gitee Pages 的自动部署
      - name: Build Gitee Pages 🔧
        uses: yanglbme/gitee-pages-action@master
        with:
          # 替换为你的 Gitee 用户名
          gitee-username: yokefellow
          # 在 Settings -> Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 替换为你的 Gitee Repo
          gitee-repo: yokefellow

  