# https://github.com/JamesIves/github-pages-deploy-action
name: Deploy GitHub Pages

# 触发条件：在 push 到 gh-pages-source 分支后
on:
  push:
    branches:
      - gh-pages-source

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 生成静态文件
      - name: Install and Build 🔧
        # 获取Vssue在Repo设置的Secret（Client ID、Client Secret）
        env: 
          ClientID: ${{ secrets.VSSUE_CLIENT_ID }}
          ClientSecret: ${{ secrets.VSSUE_CLIENT_SECRET }}
          VssueGiteeClientID: ${{ secrets.VSSUE_GITEE_CLIENT_ID }}
          VssueGiteeClientSecret: ${{ secrets.VSSUE_GITEE_CLIENT_SECRET }}
        run: |
          npm install 
          npm run build
      
      # 如果是发布到自定义域名
      # - name: Add the domain 
      #   run: cd dist && echo 'blog.yokefellow.com.cn' > CNAME

      # 部署到 GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: dist
          CLEAN: true
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee Pages🌀
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:yokefellow/yokefellow.github.io.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: " git@gitee.com:yokefellow/yokefellow.git"

      - name: Build Gitee Pages 🔧
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: yokefellow
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: yokefellow

  