name: Deploy Pages

# 触发条件：在 push 到 gh-pages-source 分支后
on:
  push:
    branches:
      - gh-pages-source

# 任务
jobs:
  # https://github.com/JamesIves/github-pages-deploy-action
  build-and-deploy:
    name: Deploy GitHub Pages
    # 服务器环境： Ubuntu（最新版）
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 生成静态文件
      - name: Install and Build Static Files 🔧
        # 获取在Repo设置的Secret（Client ID、Client Secret）
        env: 
          # Vssue Config
          Platform: github
          Owner: yokefellow
          Repo: yokefellow.github.io
          ClientID: ${{ secrets.VSSUE_CLIENT_ID }}
          ClientSecret: ${{ secrets.VSSUE_CLIENT_SECRET }}
          #Sitemap Config
          SitemapHostname: https://yokefellow.github.io
          #Google Search Console Config
          GoogleSiteVerification: iSjPDbJMyZy56rE4_RXomTvvzBmPjaJIwKf5gtB8YlQ
          #Google Analytics Config
          GoogleAnalyticsID: UA-173603129-1
        run: |
          yarn install 
          yarn run build

      # 部署到 GitHub Pages
      - name: Deploy GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: master
          publish_dir: ./dist
          commit_message: 🚀 ${{ github.event.head_commit.message }} to master from @
          enable_jekyll: true

  sync-and-build:
    name: Sync Gitee Pages
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 重新生成静态文件
      - name: Reinstall and Rebuild Static Files 🔧
        # 获取在Repo设置的Secret（Client ID、Client Secret）
        env: 
          # Vssue Config
          Platform: gitee
          Owner: yokefellow
          Repo: yokefellow
          ClientID: ${{ secrets.VSSUE_GITEE_CLIENT_ID }}
          ClientSecret: ${{ secrets.VSSUE_GITEE_CLIENT_SECRET }}
          #Sitemap Config
          SitemapHostname: https://yokefellow.gitee.io
          #Google Search Console Config
          GoogleSiteVerification: 2SVLrZXeufuyrSmPA13Wg6uD5eWehH1gfQxUTuFIdrY
          #Google Analytics Config
          GoogleAnalyticsID: UA-173603129-2
        run: |
          yarn install 
          yarn run build 

      # 将静态文件和源码同步到 Gitee Pages
      - name: Sync Gitee Pages 🌀
        uses: yokefellow/gitee-pages-deploy-action@master
        env:
          # 在 Settings -> Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 替换为你的 Gitee Pages 仓库地址
          gitee_repo: "git@gitee.com:yokefellow/yokefellow.git"
          folder: dist
          git_user_email: 1241900094@qq.com
          git_user_name: yokefellow
          # cname: blog.yokefellow.com.cn
          gitee_pages_branch: master
          commit_message: 🌀 Sync from GitHub Actions

      # 实现 Gitee Pages 的自动部署
      - name: Build Gitee Pages 🔧
        uses: yanglbme/gitee-pages-action@master
        with:
          # 替换为你的 Gitee 用户名
          gitee-username: yokefellow
          # 在 Settings -> Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 替换为你的 Gitee Repo
          gitee-repo: yokefellow
